// ── Datos centralizados de Forner Classics ──────────────────────────────

export const vehicles = [
  {
    id: 'chevrolet-1930',
    slug: 'chevrolet-1930',
    badge: 'INSIGNIA',
    badgeColor: '#C9A84C',
    name: 'Chevrolet International AC',
    year: '1930',
    era: 'Pre-War Americana',
    color: 'Negro & Caoba',
    pax: '4 pasajeros',
    description:
      'La exhibición suprema. Un porte majestuoso que detiene el tiempo y conquista las miradas. Cada curva de su carrocería es un manifiesto de artesanía que pocas épocas han sabido igualar. Inmortalice su gran día con un escenario que el tiempo no podrá borrar.',
    features: [
      'Chófer de etiqueta incluido',
      '4 pasajeros cómodamente',
      'Decoración floral personalizada',
      'Ideal para bodas de alto protocolo',
    ],
    idealFor: 'Bodas de gala · Recepciones oficiales · Eventos de protocolo',
    image: '/images/chevrolet.webp.png',
    imageAlt: 'Chevrolet International AC 1930 de Forner Classics para bodas y eventos en Gandía Valencia',
    tarifas: [
      { tipo: 'Servicio de Boda', precio: '600€' },
      { tipo: 'Servicio de Rodajes y Fotografía', precio: '320€' },
      { tipo: 'Servicio de Ruta', precio: '200€' },
    ],
    available: true,
    tag: 'El más solicitado',
  },
  {
    id: 'renault-caravelle-1962',
    slug: 'renault-caravelle-1962',
    badge: 'ICÓNICO',
    badgeColor: '#C9A84C',
    name: 'Renault Caravelle',
    year: '1962',
    era: 'Elegance Française',
    color: 'Rojo Burdeos',
    pax: '2 pasajeros',
    description:
      'Elegancia francesa destilada en líneas que desafían el olvido. Su silueta deportiva y su rojo profundo hacen de cada aparición un acontecimiento. La presencia cinematográfica que convierte cualquier producción visual en una obra de referencia.',
    features: [
      'Chófer profesional incluido',
      '2 pasajeros, máxima intimidad',
      'Carrocería coupé de época',
      'Ideal para rodajes y fotografía',
    ],
    idealFor: 'Rodajes · Sesiones fotográficas · Parejas · Escapadas exclusivas',
    image: '/images/carav.webp.png',
    imageAlt: 'Renault Caravelle Rojo 1962 de Forner Classics para rodajes y eventos en Valencia',
    tarifas: [
      { tipo: 'Servicio de Boda', precio: '500€' },
      { tipo: 'Servicio de Rodajes y Fotografía', precio: '250€' },
      { tipo: 'Servicio de Ruta', precio: '160€' },
    ],
    available: true,
    tag: 'El más fotogénico',
  },
  {
    id: 'seat-850-1968',
    slug: 'seat-850-1968',
    badge: 'MEDITERRÁNEO',
    badgeColor: '#C9A84C',
    name: 'SEAT 850',
    year: '1968',
    era: 'Made in Spain',
    color: 'Verde Menta',
    pax: '4 pasajeros',
    description:
      'Un símbolo de la modernidad española de los 60. Su color verde menta y sus formas redondeadas evocan una inocencia perdida que todos reconocen y nadie puede resistir. El protagonista perfecto para una historia con sabor mediterráneo auténtico.',
    features: [
      'Chófer incluido en todo momento',
      '4 puertas, 4 pasajeros',
      'Matrícula valenciana original V-209-650',
      'Ideal para eventos con encanto local',
    ],
    idealFor: 'Bodas íntimas · Sesiones fotográficas · Eventos culturales · Turismo',
    image: '/images/seat850i.jpg.png',
    imageAlt: 'SEAT 850 verde menta 1968 de Forner Classics para bodas y eventos en Gandía Valencia',
    tarifas: [
      { tipo: 'Servicio de Boda', precio: '440€' },
      { tipo: 'Servicio de Rodajes y Fotografía', precio: '200€' },
      { tipo: 'Servicio de Ruta', precio: '80€' },
    ],
    available: false,
    tag: 'El más encantador',
  },
  {
    id: 'renault-4-1982',
    slug: 'renault-4-1982',
    badge: 'POPULAR',
    badgeColor: '#C9A84C',
    name: 'Renault 4',
    year: '1982',
    era: 'French Countryside',
    color: 'Amarillo Sol',
    pax: '4 pasajeros',
    description:
      'El que hace sonreír a todo el mundo. El Renault 4 amarillo es alegría pura con motor. Icono de una generación y emblema de libertad, su presencia en cualquier escenario genera una magia espontánea difícil de imitar. Para experiencias que buscan la emoción más genuina.',
    features: [
      'Chófer incluido en todo servicio',
      '4 pasajeros',
      'Color amarillo sol irresistible',
      'Perfecto para turismo experiencial',
    ],
    idealFor: 'Turismo de experiencias · Rutas comarcales · Sesiones fotográficas · Talleres',
    image: '/images/renault4.webp.png',
    imageAlt: 'Renault 4 amarillo 1982 de Forner Classics para turismo y experiencias en la Comunitat Valenciana',
    tarifas: [
      { tipo: 'Servicio de Boda', precio: '350€' },
      { tipo: 'Servicio de Rodajes y Fotografía', precio: '160€' },
      { tipo: 'Servicio de Ruta', precio: '65€' },
    ],
    available: false,
    tag: 'El más alegre',
  },
];

export const services = [
  {
    id: 'bodas',
    slug: 'bodas',
    label: 'Servicio de Boda',
    title: 'Servicio de Boda',
    headline: 'Su enlace merece un escenario a la altura de su historia.',
    description: 'Es nuestra propuesta definitiva para bodas. Un servicio sin prisas, diseñado para que los novios disfruten de la máxima elegancia y tranquilidad en su día más especial.',
    features: [
      'Vehículo a elegir (Chevrolet 1930 o Renault Caravelle 1962).',
      'Chófer uniformado (siempre uno de los fundadores).',
      'Hasta 5 horas de servicio (recogida, ceremonia, fotos y llegada).',
      'Decoración nupcial completa del vehículo.',
      'Agua fría de cortesía para los traslados.',
      'Atención personalizada constante durante todo el servicio.',
    ],
    tarifas: [
      { vehiculo: 'Chevrolet International AC 1930', precio: '600€' },
      { vehiculo: 'Renault Caravelle 1962', precio: '500€' },
      { vehiculo: 'SEAT 850 1968', precio: '440€' },
      { vehiculo: 'Renault 4 1982', precio: '350€' },
    ],
    zone: 'Gandía · La Safor (Consultar otros desplazamientos)',
    image: '/images/service-bodas.png.jpg',
    imageAlt: 'Ambiente de boda de lujo con ramo de flores y luz cinematográfica para eventos Forner Classics',
    ctaLabel: 'Reservar para mi boda →',
  },
  {
    id: 'turismo',
    slug: 'turismo',
    label: 'Servicio de Ruta',
    title: 'Servicio de Ruta',
    headline: 'Redescubra el Mediterráneo con la cadencia de otra época.',
    description: 'Disfruta del placer de viajar en el tiempo con un paseo exclusivo por los rincones más emblemáticos de Gandía y los paisajes de La Safor. La esencia del mediterráneo a través de las ventanillas de un clásico.',
    features: [
      'Vehículo a elegir (Chevrolet 1930 o Renault Caravelle 1962).',
      'Chófer particular.',
      '1 hora de ruta personalizada.',
      'Parada para fotografías con el vehículo en un punto panorámico.',
    ],
    tarifas: [
      { vehiculo: 'Chevrolet International AC 1930', precio: '200€' },
      { vehiculo: 'Renault Caravelle 1962', precio: '160€' },
      { vehiculo: 'SEAT 850 1968', precio: '80€' },
      { vehiculo: 'Renault 4 1982', precio: '65€' },
    ],
    zone: 'Gandía · La Safor (Consultar otros desplazamientos)',
    image: '/images/service-turismo.png.jpg',
    imageAlt: 'Experiencia de picnic de lujo en naranjales mediterráneos con vistas panorámicas de La Safor',
    ctaLabel: 'Reservar ruta →',
  },
  {
    id: 'rodajes',
    slug: 'rodajes',
    label: 'Servicio de Rodajes y Fotografía',
    title: 'Servicio de Rodajes y Fotografía',
    headline: 'Para producciones que exigen autenticidad sin concesiones.',
    description: 'El escenario perfecto para producciones visuales. Ponemos a tu disposición nuestras joyas históricas para sesiones fotográficas, spots publicitarios, videoclips o contenido para redes sociales en una localización fija.',
    features: [
      'Vehículo a elegir (Chevrolet 1930 o Renault Caravelle 1962).',
      'Traslado del vehículo a la localización acordada (dentro de La Safor).',
      'Chófer asistente para el posicionamiento y cuidado del coche durante el set.',
      '3 horas de disponibilidad del vehículo en el sitio.',
    ],
    tarifas: [
      { vehiculo: 'Chevrolet International AC 1930', precio: '320€' },
      { vehiculo: 'Renault Caravelle 1962', precio: '250€' },
      { vehiculo: 'SEAT 850 1968', precio: '200€' },
      { vehiculo: 'Renault 4 1982', precio: '160€' },
      { vehiculo: 'Para requisitos corporativos, publicitarios o de cine personalizados, consulte presupuesto sin compromiso.', precio: '—' },
    ],
    zone: 'Gandía · La Safor (Consultar otros desplazamientos)',
    image: '/images/service-rodajes.png.jpg',
    imageAlt: 'Cámara de cine profesional en set de rodaje de lujo para producciones visuales Forner Classics',
    ctaLabel: 'Consultar para rodaje →',
  },
];

export const faqs = [
  {
    q: '¿El chófer está siempre incluido en el servicio?',
    a: 'Sí, absolutamente. Forner Classics no ofrece alquiler sin conductor bajo ninguna circunstancia. El chófer profesional forma parte esencial de la experiencia y es inseparable del servicio. Viajará con el vehículo en todo momento.',
  },
  {
    q: '¿En qué zonas operáis habitualmente?',
    a: 'Nuestra base de operaciones está en Gandía, La Safor (Valencia). Operamos habitualmente en la zona de Gandía y toda la comarca de La Safor. Para eventos fuera de esta zona geográfica, realizamos un estudio previo de viabilidad; por favor, consúltenos disponibilidad y el suplemento de desplazamiento correspondiente.',
  },
  {
    q: '¿Con cuánta antelación debo reservar?',
    a: 'Para bodas recomendamos reservar entre 6 y 12 meses antes, especialmente en temporada alta (mayo a septiembre). Para rodajes y eventos corporativos, 2 a 4 semanas suele ser suficiente. Para fechas muy especiales o en temporada alta, cuanto antes mejor: la disponibilidad es limitada para garantizar la calidad del servicio.',
  },
  {
    q: '¿Cómo funciona el proceso de reserva?',
    a: 'Es sencillo y se realiza exclusivamente a través de nuestra web: rellene el formulario oficial de solicitud seleccionando primero su vehículo y después la fecha deseada. No gestionamos reservas directas por WhatsApp para garantizar la correcta adjudicación de fechas en nuestro sistema. Una vez recibido el formulario, en menos de 24 horas recibirá una propuesta personalizada. Si acepta, se formaliza la reserva mediante un depósito.',
  },
  {
    q: '¿Podéis decorar el vehículo para la boda?',
    a: 'Sí. Ofrecemos decoración floral discreta y elegante que respeta la estética del vehículo. Trabajamos con floristas locales de confianza. También puede aportar su propia decoración, siempre que no dañe la integridad del vehículo. Lo acordaremos juntos durante la consulta previa.',
  },
  {
    q: '¿Qué ocurre si el tiempo es adverso el día del evento?',
    a: 'Tenemos protocolo para días de lluvia. El chófer llevará siempre un paraguas elegante para protegerle. El Renault Caravelle tiene capota que puede cerrarse. Para el Chevrolet 1930 se advierte de la exposición a elementos: lo analizamos caso por caso y buscamos siempre la mejor solución para su evento.',
  },
  {
    q: '¿Qué ocurre si necesito el vehículo por más tiempo del contratado?',
    a: 'No hay inconveniente. Si el evento se alarga más allá de las horas estipuladas en el paquete seleccionado, el tiempo adicional se facturará como horas extra a razón de 100€ por cada hora adicional. Siempre recomendamos prever bien los tiempos en la hoja de ruta inicial para evitar imprevistos.',
  },
];

export const UNAVAILABLE_VEHICLES = ['SEAT 850 1968', 'Renault 4 1982'];
